### ISSUE TITLE
Should retry on all db queries

### ISSUE THREAD

**Issue by pivnicek** [keboola/db-extractor-pgsql#53]
EX: connection lost on getTables query, should be retried https://github.com/keboola/db-extractor-pgsql/blob/master/src/Keboola/DbExtractor/Extractor/PgSQL.php#L395

**Comment by pivnicek** [comment]
Happened again on this line https://github.com/keboola/db-extractor-pgsql/blob/master/src/Keboola/DbExtractor/Extractor/PgSQL.php#L497

All queries need to be retry-wrapped.
ref: https://keboola.slack.com/archives/C09U3R1J4/p1561020576000900

**Comment by Halama** [comment]
Same issue on list of tables in job execution:
```
147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.ex-db-pgsql:2.5.6 container '59330357-59298561.59330358-25258-0-keboola-ex-db-pgsql' failed: (2) [2019-07-28 23:06:21] CRITICAL: PDOException:SQLSTATE[HY000]: General error: 7 server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request. {"errFile":"/code/src/Keboola/DbExtractor/Extractor/PgSQL.php","errLine":497,"errCode":"HY000","errTrace":"#0 /code/src/Keboola/DbExtractor/Extractor/PgSQL.php(497): PDO->query(' SELECT \\n ...')\n#1 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Extractor/Extractor.php(347): Keboola\\DbExtractor\\Extractor\\PgSQL->getTables(Array)\n#2 /code/src/Keboola/DbExtractor/Extractor/PgSQL.php(197): Keboola\\DbExtractor\\Extractor\\Extractor->createManifest(Array)\n#3 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(170): Keboola\\DbExtractor\\Extractor\\PgSQL->export(Array)\n#4 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(65): Keboola\\DbExtractor\\Application->runAction()\n#5 /code/run.php(60): Keboola\\DbExtractor\\Application->run()\n#6 {main}","errPrevious":""} []
```

https://keboola.slack.com/archives/C09U3R1J4/p1564355199013300
