### ISSUE TITLE
connect error should be user errorr

### ISSUE THREAD

**Issue by odinuv** [keboola/db-extractor-pgsql#77]
CRITICAL: PDOException:SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "127.0.0.1" and accepting TCP/IP connections on port 33006?

https://keboola.slack.com/archives/C09U3R1J4/p1565753598002400

```
: 147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.ex-db-pgsql:2.5.3 container '63474138-63473516.63474139-69845-0-keboola-ex-db-pgsql' failed: (2) [2019-08-14 03:32:51] CRITICAL: PDOException:SQLSTATE[08006] [7] could not connect to server: Connection refused 	Is the server running on host "127.0.0.1" and accepting 	TCP/IP connections on port 33006? {"errFile":"/code/src/Keboola/DbExtractor/Extractor/PgSQL.php","errLine":76,"errCode":7,"errTrace":"#0 /code/src/Keboola/DbExtractor/Extractor/PgSQL.php(76): PDO->__construct('pgsql:host=127....', '...', '...', Array)\n#1 /code/src/Keboola/DbExtractor/Extractor/PgSQL.php(676): Keboola\\DbExtractor\\Extractor\\PgSQL->createConnection(Array)\n#2 /code/src/Keboola/DbExtractor/Extractor/PgSQL.php(665): Keboola\\DbExtractor\\Extractor\\PgSQL->tryReconnect()\n#3 [internal function]: Keboola\\DbExtractor\\Extractor\\PgSQL->Keboola\\DbExtractor\\Extractor\\{closure}()\n#4 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/RetryProxy.php(71): call_user_func_array(Object(Closure), Array)\n#5 /code/src/Keboola/DbExtractor/Extractor/PgSQL.php(668): Keboola\\DbExtractor\\RetryProxy->call(Object(Closure))\n#6 /code/src/Keboola/DbExtractor/Extractor/PgSQL.php(489): Keboola\\DbExtractor\\Extractor\\PgSQL->runRetriableQuery('    SELECT \\n   ...')\n#7 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Extractor/Extractor.php(347): Keboola\\DbExtractor\\Extractor\\PgSQL->getTables(Array)\n#8 /code/src/Keboola/DbExtractor/Extractor/PgSQL.php(189): Keboola\\DbExtractor\\Extractor\\Extractor->createManifest(Array)\n#9 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(170): Keboola\\DbExtractor\\Extractor\\PgSQL->export(Array)\n#10 /code/vendor/keboola/db-extractor-common/src/Keboola/DbExtractor/Application.php(65): Keboola\\DbExtractor\\Application->runAction()\n#11 /code/run.php(60): Keboola\\DbExtractor\\Application->run()\n#12 {main}","errPrevious":""} []
```

**Comment by pivnicek** [comment]
Note: to fix this we should catch exceptions in the `tryReconnect()` method if they are thrown when trying to recreate the connection, and throw them as UserExceptions.
